spring:
  application:
    name: openaimp-backend
  datasource:
    url: jdbc:mysql://localhost:3306/openaimp?serverTimeZone=UTC
    username: root
    password: ${DB_PASSWORD:ab321818}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 5s
  mail:
    host: smtp.qq.com
    port: 587
    username: amstudio@qq.com
    password: ojxeivkzyineddaj
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: false
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

sa-token:
  token-name: aerionstudio
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true

server:
  port: 6067

app:
  mail:
    from: amstudio@qq.com
